_posts/2020-11-21-barami-blog.md

Add: First Post for posting test

---

Gemfile

이유는 모르겠지만 [Github Actions에서 build error](https://github.com/hyu-barami/hyu-barami.github.io/actions/runs/380901601)가 나고 
그래서 이런저런 시도를 하며 고쳐보려 시도하는 중
왠지 저 문장을 해제하면 설치가 되지 않을까? 라고 생각하고 
if문을 없애고 풀리퀘를 날려보지만 확신은 없는데 됬으면 좋겠다

Fix: Build Error

---

Gemfile

[이번 에러](https://github.com/hyu-barami/hyu-barami.github.io/runs/1447344410?check_suite_focus=true) 도 [저번 에러](https://github.com/hyu-barami/hyu-barami.github.io/pull/5) 처럼 if 문을 없애서 해결하려 시도함 
( 될지는 모르겠다.. o<-< 깃헙 액션스님 제발 돌아주세요..

Fix: build error - Delete if at wdm

---

_includes/utterance.html
_layouts/post.html

댓글 기능 utterance 추가 
댓글 이슈 저장용 레포지토리는 https://github.com/hyu-barami/hyu-blog-comment 를 사용하고 있습니다.

Add: utterance (댓글 기능)

---

_posts/2020-12-25-25th-kimjeonghyun-jinwonbot.md

#10 에서 언급하신것처럼, 링크들에 a태그를 적용했습니다.

진원봇 문서 링크 수정

---

_posts/2020-12-28-hyeonhoshin.md

hyeonho shin add

---

_includes/css-selector.html
_includes/panel.html
assets/css/barami.scss

졸업한 선배분의 요청으로 우측 메뉴에 바라미 후원 계좌 안내 문구 작성

Add: Feature/account 바라미 후원 계좌 작성

---

_includes/panel.html

Add: Feature/2020 exhibition panel

---

_posts/2020-12-28-opencv-car.md

독스 파일 제출자로, 대신 마크다운으로 변환하여 업로드 중
아직 작성중
비디오 이슈가 있는듯함

Add: parkjuntaek - opencvcar post

---

_posts/2020-12-28-FDTD-simulation.md

Add: Post 2020-12-28-FDTD-simulation.md

---

_posts/2020-12-28-FDTD-simulation.md

Modify: FDTD

---

_posts/2021-01-21-temperature-humid-measurement.md

Add: Post 온습도 관리 프로그램

---

_posts/2021-01-21-temperature-humid-measurement.md

Modify post : 온습도관리프로그램

---

_posts/2021-01-23-camera.md.md

Add:Post FPGA를 이용한 방범용 감시장치

---

_posts/2021-11-25-predict-snp500
_posts/2021-11-25-predict-snp500.md

Post: 2021년 김성근 회원님 작품

---

_posts/2021-11-26-selfparking_car.md

Add: Post 아두이노 RC카 자동주차 시스템

---

_posts/2021-11-26-custom_keyboard.md

heewon image correction

---

_posts/2021-11-23-GPS-L1-MSA.md

Add:Post GPS L1 MSA

---

_posts/2021-11-26-pythongame.md

바라미 준회원 조영일 작품 "파이썬으로 만들어 본 간단한 게임"입니다.
공학도를 위한 창의적 컴퓨팅 시간에 배웠던 내용과 제가 유튜브 및 책에서 본 내용을 가지고 만들어 본 드래곤 플라이트(에 비하면 엄청나게 퀄리티가 떨어지지만....)를 참고해서 만들어보았습니다

Add: Post 2021-11-26-pythongame.md

---

_posts/2021-11-27-dynamic_paint.md

Dynamic Paint
change image size and video size

change images and video size

---

_posts/2021-11-27-dynamic_paint.md

Dynamic paint
change video size 2(by half)

change video size 2

---

_posts/2021-11-26-pythongame.md

조영일 회원님 글 수정
